server:
  port: 8083

apiclient:
  bithumb:
    gateway:
      url: http://localhost:8082

spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:XE
    username: oracle_test
    password: 1234
    driver-class-name: oracle.jdbc.driver.OracleDriver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true #false

axon:
  serializer:
    general: xstream
  axonserver:
    servers: ${vcap.services.AxonServer.credentials.uri:localhost}

logging:
  level:
    com.example.assettemplate: debug
    org.axonframework: debug
